### ISSUE TITLE
a";echo Got your secrets"

### ISSUE THREAD

**Issue by Knt44kw** [Knt44kw/github-actions-practice#17]
issue名を環境変数とすることで

ISSUE_TITLE=a";echo Got your secrets" 全体が文字列となりスクリプトインジェクションが発生しない

```
name: Label Issues (Script Injection Example)
on:
  issues:
    types:
      - opened
jobs:
  assign-label:
    runs-on: ubuntu-latest
    steps:
      - name: Assign label
        env:
          ISSUE_TITLE: "${{ github.event.issue.title }}"
        run: |
          if [[ "$ISSUE_TITLE" == *"bug"* ]]; then
          echo "Issue is about a bug!"
          else
          echo "Issue is not about a bug"
          fi
```
